sudo: required
language: generic

services:
  - docker  

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t jangmj80/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jangmj80/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-app"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-575108946475"
  bucket_path: "docker-app"
  on:
    branch: main